version: '3'
services:
  #############
  # POSTGRES
  # https://hub.docker.com/_/postgres
  #########
  db:
    image: postgres
    restart: always
    build:
        context: ./aad_db
        dockerfile: dockerfile-db

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_JWT_SECRET=${POSTGRES_JWT_SECRET}
      - POSTGRES_API_PASSWORD=${POSTGRES_API_PASSWORD}
      - POSTGRES_JWT_CLAIMS=${POSTGRES_JWT_CLAIMS}

    #volumes:
      # anything in initdb directory is created in the database
      # - "./aad_db/sql-current:/docker-entrypoint-initdb.d"
      # Uncomment this if you want to persist the data.
      #- "~/.data/aad_db/pgdata:/var/lib/postgresql/data"

  db-api:
    image: dev-swagger-hapi-api
    #image: wilfongjt/db-api
    build:
      context: .
    command: >
      sh -c "npm install && npm install nodemon && npm run db-deploy && npm run dev"
    volumes:
      - .:/usr/src/api
    ports:
      - 5555:5555
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - PORT=${PORT}      
      - DATABASE_URL=${DATABASE_URL}
      - API_TOKEN=${API_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_CLAIMS=${JWT_CLAIMS}
 
