
# This is a basic workflow to help you get started with Actions
# remove and leave space
name: node.js CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true      

      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies 👨🏻‍💻
        run: | 
          npm ci --prefer-offline --no-audit
          npm install @hapi/lab @hapi/code
          npm run build --if-present
          
      - name: Deploy Database
        run: npm run db-deploy
        env:
          ACCEPTED_ORIGINS: ${{secrets.ACCEPTED_ORIGINS}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HOST: "0.0.0.0"
          JWT_CLAIMS: ${{secrets.JWT_CLAIMS}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          NODE_ENV: staging

      - name: Database Unit Tests
        run: npm run db-unit-test
        env:
          ACCEPTED_ORIGINS: ${{secrets.ACCEPTED_ORIGINS}}
          API_TOKEN: ${{secrets.API_TOKEN}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HOST: "0.0.0.0"
          JWT_CLAIMS: ${{secrets.JWT_CLAIMS}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          NODE_ENV: staging

      # Uncomment when heroku review, stageing, and production are available
      #- name: Run database unit tests 🧪
      #  run: npm run test
      #  env:
      #    JWT_CLAIMS: ${{secrets.JWT_CLAIMS}}
      #    JWT_SECRET: ${{secrets.JWT_SECRET}}
      #    API_TOKEN: ${{secrets.API_TOKEN}}
      #    DATABASE_URL: ${{secrets.DATABASE_URL}}
      #    HOST: "0.0.0.0"
      #    ACCEPTED_ORIGINS: ${{secrets.ACCEPTED_ORIGINS}}
      #    HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-aad-lgrow-staging" #Must be unique in Heroku
          heroku_email: "wilfongjt@gmail.com"
